In [1]:
import pandas as pd
import re

In [5]:
dataframe_final_candidatos = pd.read_csv('Etapa 2 - dataframe_final_candidatos.csv')

In [6]:
dataframe_final_candidatos

,Data_Hora,IdTweet,Tweet,Candidato
0,2022-07-31 18:09:44+00:00,1553805124279074821,Queria uma toalha do Lula,Lula
1,2022-07-31 18:09:19+00:00,1553805018721050627,@DarkWolfRJ2 @Pati_Medeiross @pauloeneas Vc ac...,Bolsonaro
2,2022-07-31 17:58:12+00:00,1553802221585850369,Paris St Germain vs Nantes is on ESPN 3 (Centr...,ciro
3,2022-07-31 17:47:24+00:00,1553799503752331267,Smorgasbord Blog Magazine - Weekly Round up Ju...,Simone
4,2022-07-31 15:43:26+00:00,1553768306275979266,@DeividWLP @pablomarcal Na base do motivaciona...,Pablo Marçal

In [7]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet']

In [8]:
dataframe_final_candidatos

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-31 18:09:44+00:00,1553805124279074821,Queria uma toalha do Lula,Lula,Queria uma toalha do Lula
1,2022-07-31 18:09:19+00:00,1553805018721050627,@DarkWolfRJ2 @Pati_Medeiross @pauloeneas Vc ac...,Bolsonaro,@DarkWolfRJ2 @Pati_Medeiross @pauloeneas Vc ac...
2,2022-07-31 17:58:12+00:00,1553802221585850369,Paris St Germain vs Nantes is on ESPN 3 (Centr...,ciro,Paris St Germain vs Nantes is on ESPN 3 (Centr...
3,2022-07-31 17:47:24+00:00,1553799503752331267,Smorgasbord Blog Magazine - Weekly Round up Ju...,Simone,Smorgasbord Blog Magazine - Weekly Round up Ju...
4,2022-07-31 15:43:26+00:00,1553768306275979266,@DeividWLP @pablomarcal Na base do motivaciona...,Pablo Marçal,@DeividWLP @pablomarcal Na base do motivaciona...

In [9]:
def limpeza_do_texto(tweet):
  tweet = tweet.lower()
  tweet = re.sub('\n', '', tweet)
  tweet = re.sub('@[^\s]+','', tweet)
  tweet = re.sub('\B#\S+', '', tweet)
  tweet = re.sub('https?://\s+|www\.\S+', '' , tweet)
  return tweet

In [10]:
dataframe_final_candidatos['Tweet_limpo'] = dataframe_final_candidatos['Tweet'].apply(lambda i:limpeza_do_texto(i))

In [11]:
dataframe_final_candidatos

,Data_Hora,IdTweet,Tweet,Candidato,Tweet_limpo
0,2022-07-31 18:09:44+00:00,1553805124279074821,Queria uma toalha do Lula,Lula,queria uma toalha do lula
1,2022-07-31 18:09:19+00:00,1553805018721050627,@DarkWolfRJ2 @Pati_Medeiross @pauloeneas Vc ac...,Bolsonaro,vc acha que eles vão reclamar. que filhos e...
2,2022-07-31 17:58:12+00:00,1553802221585850369,Paris St Germain vs Nantes is on ESPN 3 (Centr...,ciro,paris st germain vs nantes is on espn 3 (centr...
3,2022-07-31 17:47:24+00:00,1553799503752331267,Smorgasbord Blog Magazine - Weekly Round up Ju...,Simone,smorgasbord blog magazine - weekly round up ju...
4,2022-07-31 15:43:26+00:00,1553768306275979266,@DeividWLP @pablomarcal Na base do motivaciona...,Pablo Marçal,na base do motivacional... ativando eles kkk...

In [12]:
dataframe_final_candidatos.to_csv("dataframe_final_candidatos_pronto_para_sentimento.csv", sep=',', index=False)